### ISSUE TITLE
Error message rather than crash when `SLACK_TOKEN` is missing

### ISSUE THREAD

**Issue by jlumbroso** [jlumbroso/slacktivate#1]
When `SLACK_TOKEN` is not configured, the crash is brutal:
```
$ pipenv run slacktivate --spec ./configuration.yaml users activate --dry-run
Traceback (most recent call last):
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/bin/slacktivate", line 8, in <module>
    sys.exit(main())
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/lib/python3.10/site-packages/slacktivate/cli/__main__.py", line 220, in main
    return sys.exit(cli())
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/lib/python3.10/site-packages/slacktivate/cli/commands/users.py", line 123, in users_activate
    _prep_ctx(ctx=ctx, spec=spec, dry_run=dry_run)
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/lib/python3.10/site-packages/slacktivate/cli/commands/users.py", line 109, in _prep_ctx
    ctx.obj.login()
  File "/Users/jlumbroso/.local/share/virtualenvs/princeton-cs-grad-slack-TURfUYtK/lib/python3.10/site-packages/slacktivate/cli/helpers.py", line 201, in login
    os.environ["SLACK_TOKEN"] = self._slack_token_last_used
  File "/Users/jlumbroso/.asdf/installs/python/3.10.5/lib/python3.10/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/Users/jlumbroso/.asdf/installs/python/3.10.5/lib/python3.10/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType

**Comment by jlumbroso** [comment]
When accessing through CLI, [addressed by this commit](https://github.com/jlumbroso/slacktivate/commit/96e2c4781de82da49eef694c8b33ebd529959db9#diff-3608e63f3a71491f8df11a2ca8e399712f25f0c3552b478968f785c1630dd638R180-R215).
